[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true
#optimizer = true
#optimizer_runs = 100
ffi = true

[rpc_endpoints]
default_network = "https://rpc-besu.cluster.eita.cloud"
localhost = "http://127.0.0.1:8545"

# mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
# sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# gnosis = "https://rpc.gnosischain.com"
# chiado = "https://rpc.chiadochain.net"
# base = "https://mainnet.base.org"
# baseSepolia = "https://sepolia.base.org"


[etherscan]
# polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"
